export * from "./functional-patterns/map";
export * from "./functional-patterns/option";
export * from "./functional-patterns/result";
export * from "./others/contextsafetype";
export * from "./others/context-safe-type";
export * from "./others/getSetClass";
export * from "./others/tick";
export * from "./others/type-marker";
export * from "../functions/returnFromVoid";
