name: Better Standard Lib CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  better-standard-lib:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint better-standard-lib
        run: bun run lint:ci

      - name: Build better-standard-lib
        run: bun run build:ci

      - name: Run Vitest tests
        run: bun run test:vitest
